source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def testing_pods
   pod 'Quick', '~> 0.6.0'
   pod 'Nimble', '2.0.0-rc.3'
end

target 'HealthKitSampleGenerator_Example', :exclusive => true do
  pod "HealthKitSampleGenerator", :path => "../"
end

target 'HealthKitSampleGenerator_Tests', :exclusive => true do
  pod "HealthKitSampleGenerator", :path => "../"
  testing_pods
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end