source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def testing_pods
   pod 'Quick', '~> 0.6.0'
   pod 'Nimble', '2.0.0-rc.3'
end

target 'HealthKitSampleGenerator_Example', :exclusive => true do
  pod "HealthKitSampleGenerator", :path => "../"
end

target 'HealthKitSampleGenerator_Tests', :exclusive => true do
  pod "HealthKitSampleGenerator", :path => "../"
  testing_pods
end

target 'HealthKitSampleGenerator_ExampleUITests', :exclusive => true do
    pod "HealthKitSampleGenerator", :path => "../"
end
