//
//  Constants.swift
//  Pods
//
//  Created by Michael Seemann on 02.10.15.
//
//

import Foundation


public enum HealthDataToExportType : String {
    case ALL = "All"
    case ADDED_BY_THIS_APP = "Added by this app"
    case GENERATED_BY_THIS_APP = "Generated by this app"
    
    public static let allValues = [ALL, ADDED_BY_THIS_APP, GENERATED_BY_THIS_APP];
}
