//
//  Export.swift
//  Pods
//
//  Created by Michael Seemann on 02.10.15.
//
//

import Foundation
import HealthKit

public enum ExportError: ErrorType {
    case IllegalArgumentError(String)
}

public enum HealthDataToExportType : String {
    case ALL                    = "All"
    case ADDED_BY_THIS_APP      = "Added by this app"
    case GENERATED_BY_THIS_APP  = "Generated by this app"
    
    public static let allValues = [ALL, ADDED_BY_THIS_APP, GENERATED_BY_THIS_APP];
}

public typealias ExportCompletion = (ExportError?) -> Void
public typealias ExportProgress = (message: String, progressInPercent: NSNumber?) -> Void


class ExportOperation: NSOperation {
    
    var exportConfiguration: ExportConfiguration
    var healthStore: HKHealthStore
    var onProgress: ExportProgress
    
    init(
        exportConfiguration: ExportConfiguration,
        healthStore: HKHealthStore,
        onProgress: ExportProgress,
        completionBlock: (() -> Void)?
        ) {
        
        self.exportConfiguration = exportConfiguration
        self.healthStore = healthStore
        self.onProgress = onProgress
        super.init()
        self.completionBlock = completionBlock

    }
    
    override func main() {
        let jsonWriter = JsonWriter(outputStream: exportConfiguration.outputStream!)
        jsonWriter.writeArrayStart()
        self.onProgress(message: "reading HKCharacteristicTypeIdentifierDateOfBirth", progressInPercent: 0.0)

        sleep(3)
        
        
        jsonWriter.writeArrayEnd()
        self.onProgress(message: "export done", progressInPercent: 1.0)

    }
}

public struct ExportConfiguration {
    
    public var exportType = HealthDataToExportType.ALL // required
    public var profileName: String? // required
    public var outputFielName: String? // not required
    public var overwriteIfFileExist = false
    public var outputStream: NSOutputStream? // requried
    
    public init(){}
    
    public func isValid() -> Bool {
        // profile name is required
        var valid = !(profileName ?? "").isEmpty
        
        // if the outputFileName already exists, the state is only valid, if overwrite is allowed
        if let fileName = outputFielName where !fileName.isEmpty {
            if NSFileManager.defaultManager().fileExistsAtPath(fileName) {
                valid = valid && overwriteIfFileExist
            }
        }
        
        return valid
    }
}

public class HealthKitDataExporter {
    
    public static let INSTANCE = HealthKitDataExporter()
    
    let exportQueue: NSOperationQueue = {
        var queue = NSOperationQueue()
        queue.name = "export queue"
        queue.maxConcurrentOperationCount = 1
        return queue
    }()
    
    let healthStore = HKHealthStore()
    
    let healthKitTypesToRead = Set(arrayLiteral:
        HKObjectType.characteristicTypeForIdentifier(HKCharacteristicTypeIdentifierDateOfBirth)!,
        HKObjectType.characteristicTypeForIdentifier(HKCharacteristicTypeIdentifierBiologicalSex)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierHeartRate)!,
        HKObjectType.workoutType()
    )

    
    init() { }
    
    public func export(exportConfiguration: ExportConfiguration, onProgress: ExportProgress, onCompletion: ExportCompletion) -> Void {
        if(!exportConfiguration.isValid()){
            onCompletion(ExportError.IllegalArgumentError("invalid export configuration"))
            return
        }
        if(exportConfiguration.outputStream == nil){
            onCompletion(ExportError.IllegalArgumentError("the outputstream must be set"))
            return
        }
        if(exportConfiguration.outputStream!.streamStatus != .Open){
            onCompletion(ExportError.IllegalArgumentError("the outputstream must be open"))
            return
        }
                
        let exportOperation = ExportOperation(
            exportConfiguration: exportConfiguration,
            healthStore: healthStore,
            onProgress: onProgress,
            completionBlock:{
            onCompletion(nil)
        })
        
        healthStore.requestAuthorizationToShareTypes(nil, readTypes: healthKitTypesToRead) {
            (success, error) -> Void in
            self.exportQueue.addOperation(exportOperation)
            
        }
    
    }
}
